#!/bin/bash
set -eu -o pipefail

VERSION=1.8.5
PACKER_ROOT=$(dirname $(realpath $0))
ROOT=$(dirname ${PACKER_ROOT})
DOWNLOADS=${PACKER_ROOT}/.downloads
PACKER_FOLDER=${PACKER_ROOT}/.packer
PACKER=${PACKER_FOLDER}/packer-${VERSION}
ZIP_FILE=packer_${VERSION}_linux_amd64.zip

if [ ! -d ${DOWNLOADS} ]; then
    mkdir ${DOWNLOADS}
fi

if [ ! -f ${DOWNLOADS}/${ZIP_FILE} ]; then
    (cd ${DOWNLOADS} && wget https://releases.hashicorp.com/packer/${VERSION}/${ZIP_FILE})
fi

if [ ! -f ${PACKER} ]; then
    mkdir -p ${PACKER_FOLDER}
    unzip -d ${PACKER_FOLDER} ${DOWNLOADS}/${ZIP_FILE}
    mv ${PACKER_FOLDER}/packer ${PACKER}
fi

${PACKER} $*