source "https://rubygems.org"

group :development do
  # Because of https://github.com/hashicorp/vagrant/pull/10945
  gem "vagrant", git: "https://github.com/hashicorp/vagrant.git", :tag => 'v2.2.4'
end

group :plugins do
  gem "vagrant-guixsd-guest", path: "."
end