Vagrant.configure("2") do |config|
    config.vm.box = "palfrey/guixsd"
    config.vm.box_version = "1.4.0"
    config.vagrant.plugins = "vagrant-guixsd-guest"
    if Vagrant.has_plugin?("vagrant-vbguest")
        config.vbguest.auto_update = false
    end
    config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/", rsync__chown: false
end