name: Automatic Approve
on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, reopened]
jobs:
  automatic-approve:
    name: Automatic Approve
    runs-on: ubuntu-24.04
    steps:
      - name: Automatic Approve
        uses: mheap/automatic-approve-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflows: "ci.yml"